server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudbox
    username: cloudbox
    password: cloudbox
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration